# ─────────────────────────────────────────────────────────────────────────────
# agents/agent8_pdf.py  –  PDF Agent
# Renders the final reviewed paper + citations into a professional PDF.
# ─────────────────────────────────────────────────────────────────────────────

import io
import logging
from datetime import date

from reportlab.lib.pagesizes import LETTER
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, HRFlowable, PageBreak,
)
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY, TA_LEFT

logger = logging.getLogger(__name__)

# ── Colour palette ────────────────────────────────────────────────────────────
DARK_BLUE  = colors.HexColor("#1A237E")
MID_BLUE   = colors.HexColor("#283593")
LIGHT_GRAY = colors.HexColor("#F5F5F5")
RULE_COLOR = colors.HexColor("#9E9E9E")


def _build_styles() -> dict:
    base = getSampleStyleSheet()

    styles = {
        "title": ParagraphStyle(
            "PaperTitle",
            fontName="Times-Bold",
            fontSize=20,
            textColor=DARK_BLUE,
            alignment=TA_CENTER,
            spaceAfter=6,
            leading=26,
        ),
        "subtitle": ParagraphStyle(
            "Subtitle",
            fontName="Times-Italic",
            fontSize=11,
            textColor=MID_BLUE,
            alignment=TA_CENTER,
            spaceAfter=4,
        ),
        "meta": ParagraphStyle(
            "Meta",
            fontName="Times-Roman",
            fontSize=10,
            textColor=colors.grey,
            alignment=TA_CENTER,
            spaceAfter=2,
        ),
        "section_heading": ParagraphStyle(
            "SectionHeading",
            fontName="Times-Bold",
            fontSize=13,
            textColor=DARK_BLUE,
            spaceBefore=18,
            spaceAfter=6,
            leading=18,
        ),
        "body": ParagraphStyle(
            "BodyText",
            fontName="Times-Roman",
            fontSize=12,
            leading=20,
            alignment=TA_JUSTIFY,
            spaceAfter=10,
        ),
        "reference": ParagraphStyle(
            "Reference",
            fontName="Times-Roman",
            fontSize=10,
            leading=15,
            leftIndent=24,
            firstLineIndent=-24,
            spaceAfter=6,
        ),
    }
    return styles


def _add_page_number(canvas, doc):
    """Footer with page number on every page."""
    canvas.saveState()
    canvas.setFont("Times-Roman", 9)
    canvas.setFillColor(colors.grey)
    page_num = f"Page {doc.page}"
    canvas.drawCentredString(LETTER[0] / 2, 0.55 * inch, page_num)
    canvas.restoreState()


def generate_pdf(
    topic: str,
    reviewed_paper: str,
    references: list[str],
    keywords: list[str],
) -> bytes:
    """
    Render the final paper into a professional PDF.

    Args:
        topic: Paper title.
        reviewed_paper: Full reviewed paper text with ## section headers.
        references: List of formatted APA citation strings.
        keywords: Research keywords for the cover metadata.

    Returns:
        PDF file content as bytes.
    """
    logger.info("Agent 8 – Generating PDF for: %s", topic)

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=LETTER,
        leftMargin=1 * inch,
        rightMargin=1 * inch,
        topMargin=1.2 * inch,
        bottomMargin=1 * inch,
        title=topic,
        author="ResearchPilot AI",
    )

    S = _build_styles()
    story = []

    # ── Cover block ──────────────────────────────────────────────────────────
    story.append(Spacer(1, 0.4 * inch))
    story.append(Paragraph(topic, S["title"]))
    story.append(Spacer(1, 0.1 * inch))
    story.append(Paragraph("Generated by ResearchPilot AI – Multi-Agent Research System", S["subtitle"]))
    story.append(Paragraph(f"Date: {date.today().strftime('%B %d, %Y')}", S["meta"]))
    story.append(Paragraph(f"Keywords: {', '.join(keywords)}", S["meta"]))
    story.append(Spacer(1, 0.15 * inch))
    story.append(HRFlowable(width="100%", thickness=1.5, color=DARK_BLUE, spaceAfter=20))

    # ── Paper sections ────────────────────────────────────────────────────────
    import re as _re

    def style_citations(text: str) -> str:
        """Wrap [N] markers in blue superscript-style font tag for ReportLab."""
        return _re.sub(
            r'\[(\d+)\]',
            r'<font color="#6366F1"><b>[\1]</b></font>',
            text
        )

    current_lines: list[str] = []
    current_heading: str | None = None

    def flush_paragraph(lines: list[str], heading: str | None):
        if heading:
            story.append(Paragraph(heading, S["section_heading"]))
            story.append(HRFlowable(width="100%", thickness=0.5, color=RULE_COLOR, spaceAfter=6))
        text = " ".join(lines).strip()
        if text:
            for para in text.split("\n\n"):
                para = para.strip()
                if para:
                    styled = style_citations(para)
                    story.append(Paragraph(styled, S["body"]))

    for line in reviewed_paper.splitlines():
        stripped = line.strip()
        if stripped.startswith("## "):
            flush_paragraph(current_lines, current_heading)
            current_heading = stripped[3:].strip()
            current_lines = []
        else:
            current_lines.append(stripped)

    # Flush last section
    flush_paragraph(current_lines, current_heading)

    # ── References section ────────────────────────────────────────────────────
    story.append(Spacer(1, 0.3 * inch))
    story.append(Paragraph("References", S["section_heading"]))
    story.append(HRFlowable(width="100%", thickness=0.5, color=RULE_COLOR, spaceAfter=8))
    for ref in references:
        story.append(Paragraph(ref, S["reference"]))

    # ── Build PDF ─────────────────────────────────────────────────────────────
    doc.build(story, onFirstPage=_add_page_number, onLaterPages=_add_page_number)
    pdf_bytes = buffer.getvalue()
    buffer.close()

    logger.info("Agent 8 – PDF generated: %.1f KB", len(pdf_bytes) / 1024)
    return pdf_bytes
